### ISSUE TITLE
How to install this tool with microsoft account login windows 10 system?

### ISSUE THREAD

**Issue by benzBrake** [shayne/go-wsl2-host#1]
My Laptop install Windows 10 Insider Previde Build 18932 and login with microsoft account, so how can i get the real user name? I have try the microsoft account and password and it's not worked.

**Comment by shayne** [comment]
Good question, I don't use a Microsoft account.

Did you try your email / password?

Another thing to try is Start -> Run -> cmd.exe then type `net user`

**Comment by benzBrake** [comment]
It works. Thanks.
