### ISSUE TITLE
Service won't start but somehow it works

### ISSUE THREAD

**Issue by eduardoarandah** [shayne/go-wsl2-host#11]
Service won't start, either with command or doing it through windows services. 

HOWEVER, somehow the wsl line appears when executing debug.

Btw, when executing debug, hangs in "starting wslhost service"
and then I have to Ctrl-C 

```
PS C:\Users\lalo> .\wsl2host.exe start
2019/12/14 21:24:38 failed to start wsl2host: could not start service: The service cannot be started due to an error in the login.
PS C:\Users\lalo> .\wsl2host.exe debug                                                                   
wsl2host.info(1): starting wsl2host service                                                                                          
wsl2host.info(1): wsl2host-0                                                                    
wsl2host.info(1): wsl2host service stopped  
```

Another question: 

In hosts file, does order matter? 
because I've a lot of vhosts and I want to alias them all to the same wsl ip. 

Looks like the wsl line goes always at the end

**Comment by shayne** [comment]
Open up `services.msc` from Start->Run. Go to the wsl2host service Properties, Log On tab and update credentials. Click apply and try to start.
Order doesn't matter in hosts file... do you have duplicates?

**Comment by eduardoarandah** [comment]
Additional comments: 

- My system is in Spanish 
(In case the app expects some particular text in english) 

- Debug could be more verbose so it’s easier to report you any issues 

I’ll try your suggestion, thanks !

**Comment by eduardoarandah** [comment]
> Open up `services.msc` from Start->Run. Go to the wsl2host service Properties, Log On tab and update credentials. Click apply and try to start.
> Order doesn't matter in hosts file... do you have duplicates?

- No duplicates

- okk I can confirm it works by changing credentials in `services.msc`
tested commands:

start: works
stop: works
debug: stuck in "starting wsl2host service"
pause: works
continue: works

**Comment by mike-usa** [comment]
I just came across this error (and solution).  I hope someone finds this helpful.

---

**Mentionables**
1. If you entered your password wrong, it won't tell you, but the error will suggest it couldn't log on.  
2. If you log in to Windows with your Microsoft online account (encouraged for Windows 10), you need to use your _local_ account username and the password for your Microsoft (@outlook.com/@hotmail.com) account.  If you created a local admin account, you could use those credentials too.
3. Selecting "Local System account" option (listed in the image below) should also work.

---

Per the install instructions, it says to run Command Prompt as an _administrator_ and then _install_the service.  When you install, it prompts you for your credentials (username/password).  These seem to be stored with the service, visible in services.msc (image below).  If you entered your credentials wrong neither will tell you, you'll just receive a generic logon issue.

![image](https://user-images.githubusercontent.com/19392121/101203703-19dece00-3639-11eb-8160-d16b86b6fb91.png)
