### ISSUE TITLE
Could you add the hosts IP address to etc/hosts

### ISSUE THREAD

**Issue by tuhlmann** [shayne/go-wsl2-host#12]
Hi,

first of all thanks for this really helpful tool!

I run into a situation where I would like to access a service (postgres) I'm running on the Windows host from within wsl2. My solution would be to patch /etc/hosts with the IP from resolve.conf on every start. But I think it might be way better if you could add this functionality to your service as I have this running anyway.

I'm not sure if this would be the "windows.local" functionality that got removed after 0.2, if so and possible, I'd like to have it back :)

And if I may ask, it possible please add the same alias feature to it that you added for the wsl2 ip address.

Let me know if I can help testing this.

Thanks,
Torsten.

**Comment by shayne** [comment]
So postgres is running under WSL2 and you want to access from the Windows host? Using wsl2host you should be able to access it via `<distro-name>.wsl:5432`.

**Comment by tuhlmann** [comment]
Thanks for responding!

Actually I wanted it the other way around. I wanted to install Postgres in Windows and access it from the Linux guest. The main reason is I am not sure how shutdown works within wsl2. So, whenever I type `wsl --shutdown` or shutdown my machine, does that just kill the processes, or does it allow them to shutdown cleanly? Do you know about that?

I have setup Postgres in a Docker container on the Linux side for now, so that immediate problem isn't there anymore. But I can still foresee situations where it might be necessary to talk to the host from the guest side via a given IP address.

**Comment by shayne** [comment]
It's been a while, so going to close this. 

If necessary you can reference the hostname of the host. For example "my-computer-name.local". 

`wsl.exe --shutdown` shuts down all running distros, whereas `wsl.exe -t <distro>` terminates just that distro. From my testing, I can't detect a signal so it's likely a SIGKILL or similar. That said programs are generally resilient and Postgres itself uses WAL files to keep things from becoming corrupt.
