### ISSUE TITLE
Ping request fail

### ISSUE THREAD

**Issue by phelps-matthew** [shayne/go-wsl2-host#13]
Tried in v0.3.2 and v0.3.0. To get service started, I had to set logon to local system account. After starting wsl (ubuntu 18.04 in my case), and trying ```ping ubuntu1804.wsl```, ping request  could not find host. I tried creating an alias ```wsl.local``` in ```~/.wsl2hosts``` but still no response on ping. Any other diagnostics I can run to debug?

**Comment by mrcasual** [comment]
Go to services and make sure that `WSL 2 Host` is running. I had a similar issue and it was due to incorrect credentials (I swear I provided the correct ones).

**Comment by AndrejMitrovic** [comment]
Hi, I'm having the same issue. The `WSL 2 Host` is stopped in the Services tab. I tried to start it from there, but it doesn't work (no errors). What can we do to fix this?

**Comment by shayne** [comment]
Whenever Windows Insiders is upgraded it uncleanly removes the service. There's some info on the README, try reinstalling:

_NOTE: Upgrading Windows Insider will remove the service, but not cleanly. To reinstall after upgrading, first make sure you've downloaded the latest version of `wsl2host`, then run `remove` before `install`_

Open an **elevated/administrator** command prompt:

```
> .\wsl2host.exe remove
```

**Comment by AndrejMitrovic** [comment]
I've tried that, but the service is still stopped. Any other tips?

**Comment by shayne** [comment]
I'm over in Gitter if you wanna try and figure it out:
https://gitter.im/go-wsl2-host/community

**Comment by shayne** [comment]
It's possible the user account is somewhat corrupt. Check out the instructions here:
https://github.com/shayne/go-wsl2-host/issues/10#issuecomment-597399481
