### ISSUE TITLE
Bad WSL IP

### ISSUE THREAD

**Issue by yoshiyes** [shayne/go-wsl2-host#17]
New update prevents recovery of the correct ip address of the Linux VM

![image](https://user-images.githubusercontent.com/20050570/76681581-d5b42500-65f4-11ea-809d-bb6aecd25636.png)

In Ubuntu (WSL2)
![image](https://user-images.githubusercontent.com/20050570/76681601-f4b2b700-65f4-11ea-86fa-9d2d469fbc02.png)

**Comment by shayne** [comment]
Can you send me the  output of `cat /proc/net/fib_trie`?

**Comment by yoshiyes** [comment]
Here's the result 😉
[result.txt](https://github.com/shayne/go-wsl2-host/files/4333390/result.txt)

**Comment by shayne** [comment]
Download v0.3.4 from the releases page. I implemented a more robust way of finding the WSL IP.

**Comment by yoshiyes** [comment]
I confirmed that the problem has been solved ! Thanks
[image](https://user-images.githubusercontent.com/20050570/76701964-46774200-66c6-11ea-9ce2-9e5597849c8c.png)
