### ISSUE TITLE
Improperly being detected as a threat Program:Win32/Bearfoos.A!ml

### ISSUE THREAD

**Issue by jperocho** [shayne/go-wsl2-host#3]
Hi Im using your fix and found it very usefull. but I just want to let you know
that windows defender is blocking it as a threat Program:Win32/Bearfoos.A!ml. 

Again thanks for the program very useful

**Comment by shayne** [comment]
Thanks for reporting! I haven't seen that on my end (yet). Have you reported it as a false positive?

**Comment by shayne** [comment]
Were there any details in the report?

**Comment by jperocho** [comment]
Yes I send the report to windows security feedback already.
Here's the screenshot details.
![image](https://user-images.githubusercontent.com/1308925/61166427-bcd40b00-a55f-11e9-9078-1d8f165c02de.png)
