### ISSUE TITLE
[feature] Add the Windows host IP to the hosts file

### ISSUE THREAD

**Issue by resolving-ngi** [shayne/go-wsl2-host#38]
It would be helpful to add the IP of the host to be able to use it within the WSL distro for xdebug.remote_host in php.ini for example.

**Comment by CL-Jeremy** [comment]
I'm currently using this line as a startup item in task scheduler: ```powershell.exe -Command "& {wsl.exe -u root echo $(Get-NetIPAddress -InterfaceAlias """"vEthernet (WSL)"""" | select IPAddress -Skip 1 -ExpandProperty IPAddress) windows.local `>`> /tmp/hosts}"```

Also related: #14. A brief search of "windows.local" did not hit this, thus linking to older issue.
