### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by sidgrafix** [shayne/go-wsl2-host#4]
Downloaded 0.11 zip and .exe

Placed in directory on my Win10 system and extracted the zip (extracted files and .exe all in same directory, opened CMD as administrator in directory ran .\go-wsl2-host.exe install and entered my username and password when asked.

Launched Debian WSL2 

Opened HOST file no IP added and no wsl.host in list.

Stopped Debian and restarted windows.

Launched Debian, still nothing added to HOST file, running ping wsl.local returns "could not find host!

Did I do something wrong??? I would really like for this to work! updating the HOST file manually every time I reboot is a real pain.

Going to try alpha 0.1.0 now to see if that is any better!

Thank You,
sidgrafix

**Comment by sidgrafix** [comment]
UPDATE: Got it sorted-kinda

I removed 0.1.1-alpha with .\go-wsl2-host.exe remove then switched to directory with 0.1.0-alpha and ran .\go-wsl2-host.exe install (input user and password when requested.)
- launched Debian WSL2 VM
- Checked windows HOST file, nothing updated. Closed Debian...
- Ran .\go-wsl2-host.exe debug (which started the service)
- Launched Debian again
- Checked HOST file - "PROFIT", HOST file now had Debian IP listed with wsl.local as the host.

HOWEVER, once I Ctrl-C out of debug mode in CMD prompt the service reports stopping...
- Reboot system to force new IP for Debian
- Launch Debian check IP with: ip addr | grep eth0 (IP reports new/different from last boot)
- Check windows HOST file (No changes, only the previous IP was listed with wsl.host MEANING it's not working.

Next I opened Windows Services find wsl2host (service is not running and lists as automatic startup)
-Try to start service, get permissions error (which is weird considering using debug forced the service to start (while it was in debug mode,meaning credentials should be good)
- Open properties and there is a checked box saying this service might be "blocked" uncheck to allow to run, so I did, applied the changes and then rt moused and clicked start... the service started without error.
- Launched Debian and got IP, then opened windows HOST file and wsl.local reports proper IP. "PROFIT AGAIN"
- Restarted system and launched Debian again checked and saw new IP and then verified in HOST file...

All seams to be working properly now! Not sure if this is a bug or not, but I couldn't find anything else relating to the service and checking it manually so I figured it out myself and thought I would update this in case someone else ran into a similar issue.

Thank you for the utility as it eleviates a headache when dealing with the changes in IP handling between WSL2 and WSL

~sidgrafix

**Comment by mpcjanssen** [comment]
It is essential that the service is running as the same user as the WSL user. Otherwise the WSL install will not be found.

**Comment by lucaskds** [comment]
It wasn't working for me because my password was too long and the service was failing silently. So I changed the password manually on the service config(WSL2 Host). After this, it worked fine :)

**Comment by shayne** [comment]
Give 0.2.0 a try. Just released. Make sure you check the case sensitivity of your username by running `net user` from CMD.

You can always Start->Run `services.msc` and locate the `WSL2 Host` service, go to properties then the `Log On` tab and set your username and password there.

**Comment by diqidoq** [comment]
This issue isn't fixed nor has the user reported back that something else has caused this issue. Not sure why this issue is closed then.

**Comment by Narimm** [comment]
The OP reported he had resolved his issue on July 24 - the title of this issue is also unhelpful  and non specific.

**Comment by diqidoq** [comment]
> 
> The OP reported he had resolved his issue on July 24 - the title of this issue is also unhelpful and non specific.

True but... 

1.) From what I know about issue queues, is that if a title is unhelpful the title will be changed regarding the real issue to keep track of the underlying problem for later reference.

>
> UPDATE: Got it sorted-kinda

2.) Does may sound "kinda" fixed from a users perspective, but do not really sound like fixed from a developers perspective. And the follow up posts of other users sound like open questions to the maybe underlying issue at least? Never mind, Just thoughts...

PS: And do we are on Facebook here, with up and down votes? Kinda childish... What so ever ...

**Comment by sourcevault** [comment]
> You can alw

it works ! it shows `ubuntu.wsl` in host file. I assumed I had to put the `wsl` password instead of the windows local account ( in my case the password was actually a PIN )
