### ISSUE TITLE
Add config to allow multiple hostnames 

### ISSUE THREAD

**Issue by scrossan-crown** [shayne/go-wsl2-host#5]
I'd love it if there was a config file that can be used to create more than one hostname with the ip. Maybe even replace the any existing lines of the hostname with the name ip.

**Comment by foureight84** [comment]
this would be amazing. i am currently using wsl2 to run my development apps and if i could specify additional vhosts it would be convenient not having to do that manually on cold boot

**Comment by shayne** [comment]
I added support for multiple distro hostnames. It's currently config-less but I'll think about how we could do something here. Perhaps the config can live in the distro....

`~/.wsl2hosts`

It'd just contain a list of subdomains perhaps....

`
myproject.wsl
anotherexample.local
`

Thoughts?

**Comment by romeroqj** [comment]
Would be amazing! The `~/.wsl2hosts` approach is spot on IMHO.

**Comment by shayne** [comment]
Added in 345d5354ceb8f06f2f90cd317a74b3e8ae1f386e

**Comment by shayne** [comment]
Available in v0.3.0
