### ISSUE TITLE
can't write to hosts file

### ISSUE THREAD

**Issue by zipoopiz** [shayne/go-wsl2-host#57]
running .\wsl2host.exe debug,  I get the information below:
![image](https://user-images.githubusercontent.com/8112182/116012570-d1fb2a80-a65d-11eb-818c-3fc523a66a36.png)

**Comment by Houinside** [comment]
You should uncheck read-only about the hosts' property by right cilck.

**Comment by toriqo** [comment]
run wsl2host as administrator (open the terminal as administrator)
