### ISSUE TITLE
Need windows.local

### ISSUE THREAD

**Issue by miyouzi** [shayne/go-wsl2-host#58]
I don't know why dropped support for `windows.local` .

The app on WSL need to connect to  proxy server, VcXsrv, pulseaudio on Windows, I think it's useful.

**Comment by sverkera** [comment]
A workaround, if you have docker installed you can use host.docker.internal from wsl2 instance to access Windows.

**Comment by Chuanbin-Wang** [comment]
@miyouzi You can see the PR #63.

**Comment by Maple1401** [comment]
+1 i want windows.local back.

**Comment by wcb33** [comment]
It's added in latest version.
