### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by s-usr** [shayne/go-wsl2-host#6]
Hi... Thanks. I downloaded this app and managed to get it running after shortening my password as noted in the other issues here.

Readme talks about connecting from WSL/Linux to Windows/local.host. I have two questions, hopefully for the general benefit of others.

* Can the connection be done the other way around: from Windows/local.host to WSL/Linux? How?
* Can those who are experts in the field share their experience / usage examples? What are you doing with this app?

Thanks much.

**Comment by s-usr** [comment]
Sharing my experience with regards to *** Connecctivity from Windows to Linux ***

1. Windows Settings | Apps & Features | Optional Features | + Add a feature | OpenSSH Server and OpenSSH Client | Install.
2. In Windows Services, make sure that 'OpenSSH Server' and 'WSL2 Host' are started and running.
3. Start 'Command Prompt' or 'PowerShell'.
4. Attempt accessing your Linux account (for example, particle@pluto) using SSH (Secure Socket Shell).

C:\> ssh particle@pluto
Warning: Permanently added the ECDSA host key for IP address '................' to the list of known hosts.
particle@pluto's password: ..........
Microsoft Windows [Version 10.0.18980.1]
(c) 2019 Microsoft Corporation. All rights reserved.

particle@PLUTO C:\Users\user>exit
Connection to pluto closed.
C:\>

**Comment by s-usr** [comment]
Sharing my experience with regards to *** Connecctivity from Linux to the Windows Machine ***
Thus far, I could not get `ssh admin@mars` to work, but the connection worked using the IP address.
 
[particle@pluto ~]$ ssh admin@mars
ssh: Could not resolve hostname pluto: Name or service not known

[particle@pluto ~]$ ssh admin@<IP_address>
admin@<IP_address>'s password: .............
`Microsoft Windows [Version 10.0.18980.1]`
`(c) 2019 Microsoft Corporation. All rights reserved.`
admin@MARS C:\Users\Admin> exit
Connection to <IP_address> closed.
[particle@pluto ~]$

**Comment by s-usr** [comment]
Sharing my experience with regards to *** Connecctivity from Linux to WSL ***
Thus far, I could not get ssh admin@wsl.local to work. In /etc/hosts, one can see that the IP address for the wsl.local service is 172.xx.yy.zz

[particle@pluto ~]$ ssh admin@wsl.local
ssh: Could not resolve hostname wsl.local: Name or service not known
[particle@pluto ~]$ ssh admin@172.xx.yy.zz
No response. Had to stop it via Ctrl-C.
[particle@pluto ~]$ ping wsl.local
ping: wsl.local: Name or service not known

**Comment by shayne** [comment]
This tool provides a host entry on Windows pointing to the IP of the WSL distro. You may have run into an issue installing the service. It's been rewritten so give it another try. 

As far as your SSH issues you'll need to install and setup an SSH server in WSL, it doesn't come with one by default.
