### ISSUE TITLE
Event Viewer shows error logs

### ISSUE THREAD

**Issue by dioseltorre** [shayne/go-wsl2-host#61]
I noticed in Event Viewer it keeps logging failure messages even though it was able to update the hosts file.

![image](https://user-images.githubusercontent.com/14935048/138544509-a23a8b22-a840-4ed2-89e6-468ab05a4bc3.png)

**Comment by eduardoluizgs** [comment]
+1

Me too.

The host file is not update.

**Comment by wcb33** [comment]
same as #77
