### ISSUE TITLE
Program "kinda" corrupts the hosts file 

### ISSUE THREAD

**Issue by takase1121** [shayne/go-wsl2-host#8]
I think this image pretty much explains itself:
![image](https://user-images.githubusercontent.com/20792268/67499914-6a54cf80-f6b4-11e9-8666-7a4b97afb1f1.png)

However if viewed with hex viewer:
![image](https://user-images.githubusercontent.com/20792268/67499962-822c5380-f6b4-11e9-8cf7-33ef4ba5aea7.png)

We can see that there is 3-4 bytes of random data that causes the encoding to change.

**Comment by shayne** [comment]
Let me know if you still have this issue with the latest version.

**Comment by takase1121** [comment]
It looks fine now, thanks!
