### ISSUE TITLE
Service floods host file

### ISSUE THREAD

**Issue by SolomonHD** [shayne/go-wsl2-host#9]
Hi,
After installing it keeps spamming the hosts file:

![image](https://user-images.githubusercontent.com/10504925/68517132-49fc4780-0254-11ea-83e9-93de19ac7ef4.png)

Any ideas how to fix this?

**Comment by SolomonHD** [comment]
After timing it, it adds ~30 entries every 2 minutes or so.

**Comment by shayne** [comment]
Can you clear out your hosts file and re-save it? Might be \r\n line endings.

**Comment by SolomonHD** [comment]
Clearing out the host file didn't solve the issue, the 
` dockerdesktop.wsl    # managed by wsl2-host`
`dockerdesktopdata.wsl    # managed by wsl2-host`
Lines kept being generated. Interestingly once I turned off my Windows WSL2 enabled Docker off it stopped the dockerdesktop.wsl line and only the dockerdesktopdata.wsl is still being generated

**Comment by shayne** [comment]
You can download v0.3.1 from Releases and give that a try. Haven't been able to reproduce it.

Does dockerdesktop add the .wsl hosts to the hosts file itself? it may be that we're conflicting there

**Comment by SolomonHD** [comment]
It's still generating the extra entries, although the pace seems to have slowed down slightly
![image](https://user-images.githubusercontent.com/10504925/68628853-ce96d200-04af-11ea-8867-6257e2d462bd.png)

BTW this is the content of my .wsl2hosts file `wsl.local wsl.lo wsl.ll`

Am I supposed to put the .wsl2hosts in my user names home directory or the root user's home directory?

**Comment by shayne** [comment]
can you start up docker desktop and run `wsl.exe -l -v` for me?

**Comment by shayne** [comment]
Went through and made sure I was being strict about getting a valid IP back, which may be causing these docker desktop false positives.

Give this release a try and let me know.
https://github.com/shayne/go-wsl2-host/releases/tag/v0.3.2

**Comment by SolomonHD** [comment]
This latest version has fixed my issue! The endless docker desktop entries stopped. 😃 
![image](https://user-images.githubusercontent.com/10504925/68865037-1ee47e80-06c0-11ea-89ba-ea1855e57ed9.png)

**Comment by robertoandrade** [comment]
I'm still seeing this error with the latest version installed. as described in #19 I just tried clearing the hosts file from the default contents to see if it's gonna help.
